https://github.com/Dexus/pem/issues/126
Dexus/pem pull request #127
Opened 2017-08-11 13:26 UTC by papakai

I've implemented the certificate checks and added md5 hashing to getModulus.
As pointed out, i would prefer to do some piping instead of introducing md5.

I've not covered further format conversions as for our purpose the checks are important, further conversion possibilities: nice 2 have.

Best
Kai

2017-08-11 14:15 UTC, papakai commented
I've applied some fixes, as I forgot little things in hurry.
But now I don't understand why travis ci build still fails
"Testing pem.js...................Fatal error: Illegal argument null", maybe you have deeper insights @Dexus

2017-08-14 16:18 UTC, papakai commented
I just have no glue why grunt exits with code 91, maybe you can help here @Dexus?

2017-08-14 16:35 UTC, Dexus commented
Will review when i have time. I'm a bit busy until next mondey.

Von meinem iPhone gesendet

> Am 14.08.2017 um 18:18 schrieb Kai Schwarz <notifications@github.com>:
> 
> I just have no glue why grunt exits with code 91, maybe you can help here @Dexus?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-08-18 13:55 UTC, Dexus requested changes
:LGTM:

2017-08-18 13:55 UTC, Dexus commented on test/pem.js
> +            serial: Date.now(),
I think this makes the Error Code 91.

Serial need to refactored as of #84

2017-08-18 14:07 UTC, papakai commented on test/pem.js
> +            serial: Date.now(),
Ok, thanks for checking this. Sorry for asking, but can you give that some priority in the next week(s)?

2017-08-22 09:45 UTC, papakai commented
@Dexus I rewrote the checkPkcs12 test, but finally this did not change things. Maybe because other existing tests (not added by myself) are also using the serial. What I do not understand here, is why this could succeed previously in other commits I've made.

2017-08-22 13:30 UTC, papakai commented
Found the stupid issue - sorry for that. got fixed and now we're ready to merge :+1:

2017-08-22 13:46 UTC, Dexus approved these changes

2017-08-22 13:46 UTC, merged

2017-08-22 13:46 UTC, Dexus commented
Thanks, will release as soon as possible the new version

2017-08-22 14:13 UTC, papakai commented
Many thanks to you for merging :+1:

2017-08-24 15:45 UTC, papakai commented
Even though I do not want to pressure...
Any news on the npm version update? I'm just asking, because increasing version number and publishing the update to npmjs.org doesn't take more than 5 minutes :) Or do you need to include further things?

2017-08-24 16:49 UTC, Dexus commented
I need access to my home server thats all...

Von meinem iPhone gesendet

> Am 24.08.2017 um 17:45 schrieb Kai Schwarz <notifications@github.com>:
> 
> Even though I do not want to pressure...
> Any news on the npm version update? I'm just asking, because increasing version number and publishing the update to npmjs.org doesn't take more than 5 minutes :) Or do you need to include further things?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-08-30 11:23 UTC, papakai commented
@Dexus you might also think about adding me as collaborator to npm, so that I might support in future too.

2017-09-12 20:45 UTC, Dexus commented
Hi @papakai I have send you an invite: https://github.com/Dexus/pem/invitations

2017-09-13 08:27 UTC, papakai commented
@Dexus Thanks, very appreciated. I have already some ideas, but can only start with things when I have the time for it :-) At least we should start with introducing some source code beautifying with a default configuration file. That would allow to reformat code written by the community which is very important imo.

2017-09-13 11:01 UTC, Dexus commented
@papakai sure maybe you can join https://gitter.im/gosiris/siris and write me there when you finde time or write me directly at gitter to discuss what should be next etc.

2017-09-13 11:19 UTC, papakai commented
@Dexus why gosiris chat room and not PEM ? :)

2017-09-13 11:58 UTC, Dexus commented
because i only fast copy one chat link 😄